### ISSUE TITLE
LobbyApiRequests.cs CreateLobbyRequest function using empty list

### ISSUE THREAD

**Issue by DanielGameExPro** [Unity-Technologies/com.unity.multiplayer.samples.coop#683] opened 2022-06-20 09:59 UTC
..\com.unity.multiplayer.samples.coop-1.2.0-pre\Library\PackageCache\com.unity.services.lobby@1.0.1\Runtime\Apis\LobbyApiRequests.cs 
line 270

A list is being created and then its size is checked (always 0).
There seems to be something missing here.

**Comment by bartj-unity** [comment] 2022-07-28 00:03
From the Lobby side, I can confirm this is a non-issue. I understand why it's confusing, but what you're seeing is just a result of auto-generated code. _If_ any of the Lobby APIs used query params, you'd see those lists that get created actually have a size > 0, but at the moment that's never the case, so it ends up looking weird like this.

**Comment by SamuelBellomo** [comment] 2022-07-28 20:01
@DanielGameExPro I'll close this issue for now, as this seems to be more related to lobby than boss room. If you'd still like to continue this conversation with lobby folks, can you open a thread in the forums please? (or in our Discord)

**Closed by SamuelBellomo** 2022-07-28 20:01 UTC
Labels: stat:in consideration, type:feedback
